export const defaultChatProps = {
  typingSpeed: 50,
  fontSize: 12,
  fontColor: '#000000',
  fontWeight: 'normal',
  messageLineDuration: 5,
  messageDuration: 10,
  maxMessageAwait: 5,
  lastMessageDuration: 20,
  showName: true,
  isLimitDisplay: false,
  whiteList: () => [] as string[],
  displayBroadcaster: false,
  displayMod: false,
  displayVip: false,
  displayFounder: false,
  displayTier2Sub: false,
  displayTier3Sub: false,
  displaySubs: false,
  subMonthsLimit: 0,
  displayBits: false,
  cheerBitsLimit: 0,
  blackList: () => [] as string[],
}